// <auto-generated />
using CustomerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerService.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20210519091606_Customers")]
    partial class Customers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerService.Models.Customers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthdate = "20-01-1990",
                            City = "Ahemdabad",
                            ContactNo = "9090909090",
                            Email = "saloni@gmail.com",
                            FullName = "Saloni",
                            Gender = "Female"
                        },
                        new
                        {
                            ID = 2,
                            Birthdate = "2-11-1980",
                            City = "Navsari",
                            ContactNo = "9078609090",
                            Email = "Ram@gmail.com",
                            FullName = "Ram",
                            Gender = "Male"
                        },
                        new
                        {
                            ID = 3,
                            Birthdate = "12-08-1980",
                            City = "Mandsaur",
                            ContactNo = "9897654450",
                            Email = "Nayan@gmail.com",
                            FullName = "Nayan",
                            Gender = "Male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
